spring:
  datasource:
    primary:
      #无需指定，除非系统无法自动识别
      driverClassName: com.mysql.jdbc.Driver
      jdbcurl: jdbc:mysql://localhost:3306/flight?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      #连接只读数据库时配置为true， 保证安全
      readOnly: false
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connectionTimeout: 30000
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idleTimeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maxLifetime: 1800000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 15
    secondary:
      driverClassName: com.mysql.jdbc.Driver
      jdbcurl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      readOnly: false
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 15

wechat:
  domain: http://www.zxbmm.cn
  appid: wx3fd4e92d3d58ac7a
  appSecret: ddf709a5f7ef407a2d5a9e438daceec0
  appToken: oVtxkkYDu3vCkbng
  apiAddress: http://back.zxbmm.cn
  #微信商户号
  mchId: 1490515532
  #微信JS调用,这部分变量不需要根据环境去修改，生成签名的时间戳10位,一般是取时间里面的一段newDate().getTime()
  timeStamp: 1401894705
  #生成签名的时间戳10位，一般是取时间里面的一段,生成签名的随机串
  noncestr: Wm3WZYTPz0wzccnW

#接口地址
url:
  php: http://106.14.221.190:8080

scheduling:
  enabled: false