spring:
    application:
        name: springboot
    profiles:
        active: dev
    #session store type使用来存放session的存储方式，目前Spring boot中只支持redis方式
    #由于本应用暂无需将session放入redis的需求，故这里就可以将session store type设置为none
    session:
        store-type: none

    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

    #jsp 页面支持配置
#    mvc:
#      view:
#        prefix: /WEB-INF/jsp/
#        suffix: .jsp

    #h5页面 templates
    thymeleaf:
      cache: false #用于页面热部署
      encoding: UTF-8
      mode: HTML5

server:
    port: 8088

logging:
    level:
        com.dzr: DEBUG
    file: /home/wwwlogs/${spring.application.name}.log

filter:
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProps:
    - userJsp/*
    - userHtml/*
  mapProps:
    key1: value1
    key2: value2
  mapListProps:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue