spring:
  datasource:
      #无需指定，除非系统无法自动识别
      driverClassName: com.mysql.jdbc.Driver
      jdbcurl: jdbc:mysql://42.121.131.12:3306/zhenpin?useUnicode=true&characterEncoding=UTF-8
      username: zhenpin
      password: zhenpin
      #连接只读数据库时配置为true， 保证安全
      readOnly: false
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connectionTimeout: 30000
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idleTimeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maxLifetime: 1800000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 15

wechat:
  domain: http://www.zxbmm.cn
  appid: wxfb086a201e1de746
  appSecret: ee9e24f4750649cb99326bfdfa557ec3
  appToken: oVtxkkYDu3vCkbng
  #这个就是自己要保管好的私有Key了（切记只能放在自己的后台代码里，不能放在任何可能被看到源代码的客户端程序中）
  #每次自己Post数据给API的时候都要用这个key来对所有字段进行签名，生成的签名会放在Sign这个字段，API收到Post数据的时候也会用同样的签名算法对Post过来的数据进行签名和验证
  #收到API的返回的时候也要用这个key来对返回的数据算下签名，跟API的Sign数据进行比较，如果值不一致，有可能数据被第三方给篡改
  key: DShengshiKTVwechat4501AToFu0N5jD
  #本项目微信支付异步通知地址
  notifyUrl: http://www.zxbmm.cn/wechat/pay/notify
  #sdk的版本号
  sdkVersion: java sdk 1.0.1
  apiAddress:
  #微信商户号
  mchId: 1490515532
  #微信JS调用,这部分变量不需要根据环境去修改，生成签名的时间戳10位,一般是取时间里面的一段newDate().getTime()
  timeStamp: 1401894705
  #生成签名的时间戳10位，一般是取时间里面的一段,生成签名的随机串
  noncestr: Wm3WZYTPz0wzccnW

#接口地址
url:
  php: http://back.zxbmm.cn

#通知模板
template:
  #购买成功
  buySuss: F1XimexykWgRCllGIyu7K2LAT4QY-H-OkXs-JJ00rX8

#定时器开关
scheduling:
  enabled: false